/**
 * Session Export Types
 *
 * Types for session export and reporting.
 */

// ─── SessionReport ────────────────────────────────────────────────────────────

/**
 * Summary report for a session.
 * Generated by SessionExporter.generateReport().
 */
export interface SessionReport {
  /** The session's unique identifier */
  sessionId: string;

  /** Total active duration in milliseconds */
  totalDuration: number;

  /** Per-event-type counts */
  eventBreakdown: Record<string, number>;

  /** Summary of errors encountered in the session */
  errorSummary: ErrorSummary;

  /** Operator actions performed during the session */
  operatorActions: OperatorActionRecord[];

  /** Health alerts triggered during the session */
  healthAlerts: HealthAlertRecord[];

  /** ISO 8601 timestamp when this report was generated */
  generatedAt: string;
}

/**
 * Aggregated error statistics for a session.
 */
export interface ErrorSummary {
  /** Total number of errors */
  total: number;

  /** Error rate (errors / total events), 0 when no events */
  rate: number;

  /** Fatal error count */
  fatalCount: number;

  /** Error messages encountered */
  messages: string[];
}

/**
 * A record of a single operator action.
 */
export interface OperatorActionRecord {
  /** The action type (e.g. pause, resume, end) */
  action: string;

  /** Optional target of the action */
  target?: string;

  /** When the action occurred (epoch ms) */
  timestamp: number;
}

/**
 * A record of a health alert.
 */
export interface HealthAlertRecord {
  /** Alert severity */
  severity: "warning" | "critical";

  /** Human-readable alert message */
  message: string;

  /** Optional component name */
  component?: string;

  /** When the alert was detected (epoch ms) */
  timestamp: number;
}

// ─── Export format ────────────────────────────────────────────────────────────

export type ExportFormat = "json" | "csv";
